### ISSUE TITLE
Chromedriver doesn't download

### ISSUE THREAD

**Issue by blgastesi** [heroku/heroku-buildpack-chromedriver#55] opened 2023-08-20 07:22 UTC
Hi there, 

I cannot deploy my application any more, as the buildpack doesn't seem to be able to download cromedriver

```
-----> Downloading chromedriver v114.0.5735.90...
Archive:  /tmp/chromedriver.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/chromedriver.zip or
        /tmp/chromedriver.zip.zip, and cannot find /tmp/chromedriver.zip.ZIP, period.
 !     Push rejected, failed to compile chromedriver app.
 !     Push failed
```

**Comment by edmorley** [comment] 2023-08-21 12:11
The new download URLs as of (#51) don't have older chromedriver versions available.

You will need to either:
- unset the `CHROMEDRIVER_VERSION` env var, so that this buildpack uses the default of the latest version automatically
- or, update the `CHROMEDRIVER_VERSION` env var to explicitly point to a newer version
- or, if you absolutely need an older chromedriver version, pin to an older release of this buildpack (use a buildpack URL of `https://github.com/heroku/heroku-buildpack-chromedriver.git#f69aa976a252665d0f2203f9852a45764c072bed`)

I've also opened #56 and #57 to improve the error message seen (since at the moment it's hard to realise what the cause is).

**Comment by sfavrinlumint** [comment] 2023-08-21 19:44
Hey @edmorley we're trying to pin the buildpack's version to a specific SHA following [Heroku's documentation](https://devcenter.heroku.com/articles/buildpacks#buildpack-references) but it's not working, do you know if this is the correct way of pinning it?

```
https://github.com/heroku/heroku-buildpack-chromedriver.git#f69aa97
```

The error is:

```-----> Creating google-chrome shims
 !     error fetching custom buildpack https://github.com/heroku/heroku-buildpack-chromedriver.git#f69aa97
 !     Push failed
```

**Comment by edmorley** [comment] 2023-08-21 19:55
Ah, I've just checked the build system implementation and it looks like if using a SHA (as opposed to git tag or branch name) for a buildpack URL, then the full 40 character SHA needs to be used (and not the short/truncated SHA). I've updated the docs to mention this:
https://devcenter.heroku.com/articles/buildpacks#buildpack-references

**Comment by sfavrinlumint** [comment] 2023-08-21 19:56
That was it, thank you so much for the prompt response! @edmorley

**Comment by edmorley** [comment] 2023-09-19 08:05
Closing this out since the cause of the failed download is due to older versions not existing, and the error messages have been made clearer in #56 and #57.

**Closed as completed by edmorley** 2023-09-19 08:05 UTC
